# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNFirebaseStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for RNFirebaseStarter

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 4.13.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  use_frameworks!
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
 
  
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport']
    pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
    pod 'React/RCTImage', :path => '../node_modules/react-native'
    pod 'React/RCTNetwork', :path => '../node_modules/react-native'
    pod 'React/RCTText', :path => '../node_modules/react-native'
    pod 'React/RCTWebSocket', :path => '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end
